// SEED_PHRASES - Comprehensive Dagbani phrase list for Dagban Kurli
// Contributors can add more; these appear as built-in content
const SEED_PHRASES = [
  // Common signs
  { dagbani: 'Piligu', english: 'OPEN', category: 'common_signs' },
  { dagbani: 'Dabi', english: 'CLOSED', category: 'common_signs' },
  { dagbani: 'Kpe soli', english: 'ENTRANCE', category: 'common_signs' },
  { dagbani: 'Yihi soli', english: 'EXIT', category: 'common_signs' },
  { dagbani: 'Tuhi', english: 'PUSH', category: 'common_signs' },
  { dagbani: 'Gbaai', english: 'PULL', category: 'common_signs' },
  { dagbani: 'Baanjira', english: 'TOILET', category: 'common_signs' },
  { dagbani: 'Doba', english: 'MEN', category: 'common_signs' },
  { dagbani: 'Paya', english: 'WOMEN', category: 'common_signs' },
  { dagbani: 'Di di', english: 'FORBIDDEN', category: 'common_signs' },
  // Basics
  { dagbani: 'N doo', english: 'Hello', category: 'basics' },
  { dagbani: 'N doo', english: 'Hello (informal)', category: 'basics' },
  { dagbani: 'Ka di be wula?', english: 'How are you?', category: 'basics' },
  { dagbani: 'M mali alaafei, m paɣiya', english: 'Fine, thank you', category: 'basics' },
  { dagbani: 'A yuli?', english: 'What is your name?', category: 'basics' },
  { dagbani: 'N yuli booni _____', english: 'My name is ______', category: 'basics' },
  { dagbani: 'Di niŋ ma suhupiɛli pam ni n ni nyaa ŋɔ', english: 'Nice to meet you', category: 'basics' },
  { dagbani: 'Dimi suɣulo', english: 'Please', category: 'basics' },
  { dagbani: 'M puhiya ka paɣi', english: 'Thank you', category: 'basics' },
  { dagbani: 'Naawuni deemi suhugu', english: "You're welcome", category: 'basics' },
  { dagbani: 'iin', english: 'Yes', category: 'basics' },
  { dagbani: 'aayi', english: 'No', category: 'basics' },
  { dagbani: 'Gaafara', english: 'Excuse me (getting attention)', category: 'basics' },
  { dagbani: 'Gaafara, n tum taali', english: 'Excuse me (begging pardon)', category: 'basics' },
  { dagbani: 'N tumi taali', english: "I'm sorry", category: 'basics' },
  { dagbani: 'Naawuni ni sɔŋ', english: 'Goodbye', category: 'basics' },
  { dagbani: 'Bai bai', english: 'Goodbye (informal)', category: 'basics' },
  { dagbani: 'N ku tooi yɛli Dagbanli [viɛnyɛla]', english: "I can't speak Dagbani [well]", category: 'basics' },
  { dagbani: 'N ni tooi yɛli silimiinsilii?', english: 'Do you speak English?', category: 'basics' },
  { dagbani: 'So be kpe ka yari silimiinsilii?', english: 'Is there someone here who speaks English?', category: 'basics' },
  { dagbani: 'Sɔŋmi ya ma!', english: 'Help!', category: 'basics' },
  { dagbani: 'Lihi ma!', english: 'Look out!', category: 'basics' },
  { dagbani: 'Dasiba', english: 'Good morning', category: 'basics' },
  { dagbani: 'Antire', english: 'Good evening', category: 'basics' },
  { dagbani: 'Aninwula', english: 'Good night', category: 'basics' },
  { dagbani: 'Naawuni ni ti biɛɣu', english: 'Good night (to sleep)', category: 'basics' },
  { dagbani: 'N bi gbaai', english: "I don't understand", category: 'basics' },
  { dagbani: 'Ya polo ka baanjira be?', english: 'Where is the toilet?', category: 'basics' },
  // Problems
  { dagbani: 'Zaŋ ma bahi', english: 'Leave me alone', category: 'problems' },
  { dagbani: 'Di shihi ma!', english: "Don't touch me!", category: 'problems' },
  { dagbani: "N yɛn bol'la prinsi", english: "I'll call the police", category: 'problems' },
  { dagbani: 'Polinga!', english: 'Police!', category: 'problems' },
  { dagbani: 'Zani ma! Tayiɣa!', english: 'Stop! Thief!', category: 'problems' },
  { dagbani: 'M bori la a sɔŋsim', english: 'I need your help', category: 'problems' },
  { dagbani: 'Nimmohi m bala', english: "It's an emergency", category: 'problems' },
  { dagbani: 'N tumla n soli', english: "I'm lost", category: 'problems' },
  { dagbani: 'N labi la m baagi', english: 'I lost my bag', category: 'problems' },
  { dagbani: 'N labi la m poochibila', english: 'I lost my wallet', category: 'problems' },
  { dagbani: 'M bɛri mi', english: "I'm sick", category: 'problems' },
  { dagbani: 'N nyɛla daŋa', english: "I've been injured", category: 'problems' },
  { dagbani: 'N bori la dɔɣite', english: 'I need a doctor', category: 'problems' },
  { dagbani: 'n ni tooi zaŋ a phone ŋɔ n niŋ m bini ŋɔ?', english: 'Can I use your phone?', category: 'problems' },
  // Numbers
  { dagbani: 'Ndam', english: '1', category: 'numbers' },
  { dagbani: 'Ayi', english: '2', category: 'numbers' },
  { dagbani: 'Ata', english: '3', category: 'numbers' },
  { dagbani: 'Anahi', english: '4', category: 'numbers' },
  { dagbani: 'Anu', english: '5', category: 'numbers' },
  { dagbani: 'Ayobu', english: '6', category: 'numbers' },
  { dagbani: 'Apɔin', english: '7', category: 'numbers' },
  { dagbani: 'Anii', english: '8', category: 'numbers' },
  { dagbani: 'Awɔi', english: '9', category: 'numbers' },
  { dagbani: 'Pia', english: '10', category: 'numbers' },
  { dagbani: 'piniyini', english: '11', category: 'numbers' },
  { dagbani: 'pinaayi', english: '12', category: 'numbers' },
  { dagbani: 'pinaata', english: '13', category: 'numbers' },
  { dagbani: 'pinaanahi', english: '14', category: 'numbers' },
  { dagbani: 'pinaanu', english: '15', category: 'numbers' },
  { dagbani: 'pinaayobu', english: '16', category: 'numbers' },
  { dagbani: 'pinaapɔin', english: '17', category: 'numbers' },
  { dagbani: 'pishiayika', english: '18', category: 'numbers' },
  { dagbani: 'pisiyinika', english: '19', category: 'numbers' },
  { dagbani: 'pishi', english: '20', category: 'numbers' },
  { dagbani: 'pishi ni yini', english: '21', category: 'numbers' },
  { dagbani: 'pishi ni ayi', english: '22', category: 'numbers' },
  { dagbani: 'pishi ni ata', english: '23', category: 'numbers' },
  { dagbani: 'Pishi ni anahi', english: '24', category: 'numbers' },
  { dagbani: 'Pishi ni anu', english: '25', category: 'numbers' },
  { dagbani: 'Pishi ni ayobu', english: '26', category: 'numbers' },
  { dagbani: 'Pishi ni apɔin', english: '27', category: 'numbers' },
  { dagbani: 'Pihita ayika', english: '28', category: 'numbers' },
  { dagbani: 'Pihitayinika', english: '29', category: 'numbers' },
  { dagbani: 'pihita', english: '30', category: 'numbers' },
  { dagbani: 'pihinahi', english: '40', category: 'numbers' },
  { dagbani: 'pihinu', english: '50', category: 'numbers' },
  { dagbani: 'pihiyobu', english: '60', category: 'numbers' },
  { dagbani: 'pisopɔin', english: '70', category: 'numbers' },
  { dagbani: 'pihinii', english: '80', category: 'numbers' },
  { dagbani: 'pihiwɔi', english: '90', category: 'numbers' },
  { dagbani: 'kɔbiga', english: '100', category: 'numbers' },
  { dagbani: 'kɔbishiyi', english: '200', category: 'numbers' },
  { dagbani: 'kɔbisita', english: '300', category: 'numbers' },
  { dagbani: 'tuhili', english: '1,000', category: 'numbers' },
  { dagbani: 'tusaayi', english: '2,000', category: 'numbers' },
  { dagbani: 'tuhi tuhaayi', english: '1,000,000', category: 'numbers' },
  { dagbani: 'tuhi tuhaata', english: '1,000,000,000', category: 'numbers' },
  { dagbani: 'tuhi tuhi anahi', english: '1,000,000,000,000', category: 'numbers' },
  { dagbani: 'pirigili', english: 'half', category: 'numbers' },
  { dagbani: 'bɛla', english: 'less', category: 'numbers' },
  { dagbani: 'pam', english: 'more', category: 'numbers' },
  // Time
  { dagbani: 'Saha', english: 'Time', category: 'time' },
  { dagbani: 'punpɔŋɔ', english: 'now', category: 'time' },
  { dagbani: 'di yi too bɛla', english: 'later', category: 'time' },
  { dagbani: 'pɔi', english: 'before', category: 'time' },
  { dagbani: 'asiba', english: 'morning', category: 'time' },
  { dagbani: 'wuntaŋni', english: 'afternoon', category: 'time' },
  { dagbani: 'zaawuni', english: 'evening', category: 'time' },
  { dagbani: 'yuŋ', english: 'night', category: 'time' },
  // Clock time
  { dagbani: 'yuŋ tisuɣu kurigi yini', english: 'one o\'clock AM', category: 'clock_time' },
  { dagbani: 'yuŋ tisuɣu kurigi ayi', english: 'two o\'clock AM', category: 'clock_time' },
  { dagbani: 'wuntaŋ zuɣusaa', english: 'noon', category: 'clock_time' },
  { dagbani: 'wuntaŋni kurigi yini', english: 'one o\'clock PM', category: 'clock_time' },
  { dagbani: 'wuntaŋni kurigi ayi', english: 'two o\'clock PM', category: 'clock_time' },
  { dagbani: 'yuŋ tisuɣu', english: 'midnight', category: 'clock_time' },
  // Duration
  { dagbani: 'minti _____', english: '_____ minute(s)', category: 'duration' },
  { dagbani: 'hawa _____', english: '_____ hour(s)', category: 'duration' },
  { dagbani: 'bakɔi _____', english: '_____ week(s)', category: 'duration' },
  { dagbani: 'goli', english: '1 month', category: 'duration' },
  { dagbani: 'chiraayi', english: '2 months', category: 'duration' },
  // Days
  { dagbani: 'zuŋɔ', english: 'today', category: 'days' },
  { dagbani: 'Sɔhila', english: 'yesterday', category: 'days' },
  { dagbani: 'biɛɣuni', english: 'tomorrow', category: 'days' },
  { dagbani: 'bakɔi ŋɔ', english: 'this week', category: 'days' },
  { dagbani: 'bakɔi din gari la', english: 'last week', category: 'days' },
  { dagbani: 'bakɔi din kani na', english: 'next week', category: 'days' },
  { dagbani: 'Alahari', english: 'Sunday', category: 'days' },
  { dagbani: 'Atani', english: 'Monday', category: 'days' },
  { dagbani: 'Atalaata', english: 'Tuesday', category: 'days' },
  { dagbani: 'Alaaba', english: 'Wednesday', category: 'days' },
  { dagbani: 'Alaamish', english: 'Thursday', category: 'days' },
  { dagbani: 'Alizumah', english: 'Friday', category: 'days' },
  { dagbani: 'Asibiri', english: 'Saturday', category: 'days' },
  // Colors
  { dagbani: 'sabinli', english: 'black', category: 'colors' },
  { dagbani: 'piɛlli', english: 'white', category: 'colors' },
  { dagbani: 'tampilim', english: 'grey/gray', category: 'colors' },
  { dagbani: 'ʒɛɛ', english: 'red', category: 'colors' },
  { dagbani: 'nuɣiso', english: 'blue', category: 'colors' },
  { dagbani: 'dozim', english: 'yellow', category: 'colors' },
  { dagbani: 'vagahili', english: 'green', category: 'colors' },
  { dagbani: 'saliŋkom', english: 'orange', category: 'colors' },
  { dagbani: 'taŋkpaɣu', english: 'brown', category: 'colors' },
  // Bus and train
  { dagbani: 'Ala n nyɛ tiɣiti zaŋ chaŋ _____?', english: 'How much is a ticket to _____?', category: 'bus_and_train' },
  { dagbani: 'Tiɣiti zaɣa yini zaŋ chaŋ _____, dimisuɣulo', english: 'One ticket to _____, please', category: 'bus_and_train' },
  { dagbani: 'Ya polo ka loori ŋɔ chana?', english: 'Where does this train/bus go?', category: 'bus_and_train' },
  { dagbani: 'Ya polo ka loori ŋɔ chana?', english: 'Where is the train/bus to _____?', category: 'bus_and_train' },
  { dagbani: "loori ŋɔ ni zan' _____", english: 'Does this train/bus stop in _____?', category: 'bus_and_train' },
  { dagbani: 'Bo saha ka ziligi maa/boosu chana?', english: 'When does the train/bus for _____ leave?', category: 'bus_and_train' },
  { dagbani: 'Bo saha ka ziligi ŋɔ/boosu yan kana?', english: 'When will this train/bus arrive in _____?', category: 'bus_and_train' },
  // Directions
  { dagbani: 'Wula ka n-yɛn chaŋ _____?', english: 'How do I get to _____?', category: 'directions' },
  { dagbani: 'Ziligi teesa?', english: '...the train station?', category: 'directions' },
  { dagbani: 'Boosu teesa?', english: '...the bus station?', category: 'directions' },
  { dagbani: 'Alapele paaki ni?', english: '...the airport?', category: 'directions' },
  { dagbani: 'ŋmaligim nuzaa', english: 'Turn left', category: 'directions' },
  { dagbani: 'ŋmaligim nudirigu', english: 'Turn right', category: 'directions' },
  { dagbani: 'Nuzaa', english: 'left', category: 'directions' },
  { dagbani: 'Nudirigu', english: 'right', category: 'directions' },
  { dagbani: 'Zaŋ kpa', english: 'towards the _____', category: 'directions' },
  { dagbani: 'petiro shɛl', english: 'gas (petrol) station', category: 'driving' },
  { dagbani: 'petiro', english: 'petrol', category: 'driving' },
  { dagbani: 'diesel', english: 'diesel', category: 'driving' },
  // Authority
  { dagbani: 'N bi tum taali shɛli', english: "I haven't done anything wrong", category: 'authority' },
  { dagbani: 'Nangbankpeen n di nyɛli', english: 'It was a misunderstanding', category: 'authority' },
  { dagbani: 'Ya ka a mali ma n chana?', english: 'Where are you taking me?', category: 'authority' },
  { dagbani: 'A gbaai ma mi maa?', english: 'Am I under arrest?', category: 'authority' },
  { dagbani: 'N nyɛla Amarika/Australia/Britin/Canada bilichina', english: 'I am an American/Australian/British/Canadian citizen', category: 'authority' },
  { dagbani: 'M bori mi ni n di Amarika/Australia/Britin/Canada embassy kpamba alizama', english: 'I want to talk to the American/Australian/British/Canadian embassy/consulate', category: 'authority' },
  { dagbani: 'M bori looya ni n di o fiila', english: 'I want to talk to a lawyer', category: 'authority' },
  { dagbani: 'Ni tooi yo n samli puŋpɔŋɔ?', english: 'Can I just pay a fine now?', category: 'authority' }
];
